const KEY='inoxcenter-incidents-v2';
let state={view:'login',code:'',filter:'Todas',selected:null,period:'Mes',dark:localStorage.getItem('inoxcenter-dark')==='1',history:[]};
const demo=[
{id:'INC-00481',title:'Caja dañada en expedición',desc:'Caja recibida con el palé roto y producto dañado en la esquina.',zone:'Expedición',priority:'Media',status:'En proceso',date:'2026-09-18T09:17:00',updated:'2026-09-18T10:03:00',creator:'Encargado 1',img:'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=700&q=75'},
{id:'INC-00482',title:'Fuga de agua en pasillo',desc:'Se detecta agua en el pasillo de instalaciones.',zone:'Instalaciones',priority:'Alta',status:'Nueva',date:'2026-09-18T10:24:00',updated:'2026-09-18T10:24:00',creator:'Encargado 1',img:''},
{id:'INC-00483',title:'Luz fundida en almacén',desc:'Punto de luz sin funcionar.',zone:'Almacén',priority:'Baja',status:'Resuelta',date:'2026-09-17T16:03:00',updated:'2026-09-17T17:10:00',creator:'Encargado 1',img:''},
{id:'INC-00484',title:'Puerta no cierra bien',desc:'La puerta de acceso no cierra correctamente.',zone:'Instalaciones',priority:'Media',status:'En proceso',date:'2026-09-12T08:40:00',updated:'2026-09-12T09:00:00',creator:'Encargado 1',img:''},
{id:'INC-00485',title:'Producto derramado',desc:'Producto derramado junto a una ubicación de almacén.',zone:'Almacén',priority:'Alta',status:'Resuelta',date:'2026-09-11T11:15:00',updated:'2026-09-11T12:00:00',creator:'Encargado 1',img:''}
];
function load(){try{return JSON.parse(localStorage.getItem(KEY))||demo}catch{return demo}}
let incidents=load();
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(incidents));return true}catch(e){alert('No se pudo guardar. Reduce el tamaño de la foto e inténtalo de nuevo.');return false}};
const fmt=d=>new Date(d).toLocaleString('es-ES',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});
const badge=s=>'<span class="badge '+(s==='Resuelta'?'resolved':s==='Nueva'?'new':'')+'">'+s+'</span>';
function go(view){if(state.view!==view)state.history.push(state.view);state.view=view;render()}
function nav(){return '<nav class="nav" aria-label="Navegación principal">'+[['home','⌂','Inicio'],['list','▤','Evidencias'],['stats','▥','Estadísticas'],['settings','⚙','Ajustes']].map(x=>'<button data-view="'+x[0]+'" class="'+(state.view===x[0]?'on':'')+'"><b>'+x[1]+'</b><small>'+x[2]+'</small></button>').join('')+'</nav>'}
function shell(title,body,back=false){return '<main class="app '+(state.dark?'dark':'')+'"><header class="top">'+(back?'<button class="back" id="back" aria-label="Volver">‹</button>':'<span></span>')+'<h1>'+title+'</h1><span class="avatar">E</span></header>'+body+nav()+'</main>'}
function login(){return '<div class="login"><div class="loginbox"><div class="brand">Inoxcenter</div><div class="warn">!</div><h1>Incidencias PRO</h1><p>Comunica. Gestiona. Soluciona.</p><section class="pinbox"><b>Introduce tu código</b><div class="dots">'+Array.from({length:5},(_,i)=>'<i class="'+(i<state.code.length?'filled':'')+'"></i>').join('')+'</div><div id="err" class="error"></div><div class="keypad">'+[1,2,3,4,5,6,7,8,9,'⌫',0,'→'].map(n=>'<button data-key="'+n+'">'+n+'</button>').join('')+'</div></section><small>Acceso restringido</small></div></div>'}
function listHTML(items){if(!items.length)return '<div class="empty">No hay incidencias en este filtro</div>';return items.map(i=>'<button class="inc" data-id="'+i.id+'" aria-label="Abrir '+i.title+'"><div class="thumb">'+(i.img?'<img src="'+i.img+'" alt="">':'▧')+'</div><div class="incbody"><h3>'+i.title+'</h3><div class="meta">'+fmt(i.date)+' · '+i.zone+'</div>'+badge(i.status)+'</div><b class="more">›</b></button>').join('')}
function home(){let p=incidents.filter(i=>i.status==='Nueva').length,e=incidents.filter(i=>i.status==='En proceso').length,today=new Date().toDateString(),r=incidents.filter(i=>i.status==='Resuelta'&&new Date(i.updated||i.date).toDateString()===today).length;return shell('Inicio','<section class="welcome"><h2>Hola, Encargado</h2><p>Aquí puedes comunicar nuevas incidencias</p><button class="primary" data-view="create">＋ &nbsp; Nueva incidencia</button><div class="stats"><div class="stat red"><b>'+p+'</b><small>Pendientes</small></div><div class="stat amber"><b>'+e+'</b><small>En proceso</small></div><div class="stat green"><b>'+r+'</b><small>Resueltas hoy</small></div></div></section><div class="sectionhead"><h2>Últimas incidencias</h2><button data-view="list">Ver todas ›</button></div><section class="card">'+listHTML(incidents.slice().reverse().slice(0,4))+'</section>')}
function list(){let tabs=[['Todas','Todas'],['Pendientes','Nueva'],['En proceso','En proceso'],['Resueltas','Resuelta']];let arr=state.filter==='Todas'?incidents:incidents.filter(i=>i.status===state.filter);return shell('Incidencias','<section class="tabs">'+tabs.map(([lab,val])=>'<button data-filter="'+val+'" class="'+(state.filter===val?'active':'')+'">'+lab+'</button>').join('')+'</section><section class="card listcard">'+listHTML(arr.slice().reverse())+'</section>')}
function create(){return shell('Nueva incidencia','<section class="card form"><label class="photoUpload"><input id="photo" type="file" accept="image/*" capture="environment"><img id="preview" alt=""><span>▣ &nbsp; Añadir / cambiar foto</span></label><label>Título de la incidencia *</label><input id="title" placeholder="Ej. Caja dañada en expedición"><label>Descripción</label><textarea id="desc" placeholder="Explica brevemente qué ha ocurrido"></textarea><label>Zona / Departamento</label><select id="zone"><option>Expedición</option><option>Almacén</option><option>Instalaciones</option><option>Maquinaria</option><option>Otros</option></select><label>Prioridad</label><select id="priority"><option>Baja</option><option selected>Media</option><option>Alta</option></select><button class="primary savebtn" id="save">Guardar incidencia</button></section>',true)}
function detail(){let i=incidents.find(x=>x.id===state.selected);if(!i){state.view='list';return list()}return shell('Incidencia #'+i.id,'<section class="card detail">'+(i.img?'<img class="detail-photo" src="'+i.img+'">':'<div class="photoempty">Sin fotografía</div>')+badge(i.status)+'<h2>'+i.title+'</h2><div class="row"><span>Fecha y hora</span><b>'+fmt(i.date)+'</b></div><div class="row"><span>Zona</span><b>'+i.zone+'</b></div><div class="row"><span>Prioridad</span><b>● '+i.priority+'</b></div><label>Descripción</label><p>'+i.desc+'</p><div class="row"><span>Creada por</span><b>'+i.creator+'</b></div><div class="row"><span>Última actualización</span><b>'+fmt(i.updated||i.date)+'</b></div><div class="actions"><button id="edit">✎ Editar</button><button class="primary" id="status">Cambiar estado</button></div></section>',true)}
function periodItems(){let now=new Date(),start=new Date(0);if(state.period==='Hoy')start=new Date(now.getFullYear(),now.getMonth(),now.getDate());if(state.period==='Semana'){start=new Date(now);start.setDate(now.getDate()-6);start.setHours(0,0,0,0)}if(state.period==='Mes')start=new Date(now.getFullYear(),now.getMonth(),1);if(state.period==='Año')start=new Date(now.getFullYear(),0,1);return incidents.filter(i=>new Date(i.date)>=start)}
function stats(){let data=periodItems(),total=data.length,res=data.filter(i=>i.status==='Resuelta').length,proc=data.filter(i=>i.status==='En proceso').length,pend=data.filter(i=>i.status==='Nueva').length;let zones={};data.forEach(i=>zones[i.zone]=(zones[i.zone]||0)+1);return shell('Estadísticas','<section class="period">'+['Hoy','Semana','Mes','Año'].map(p=>'<button data-period="'+p+'" class="'+(state.period===p?'active':'')+'">'+p+'</button>').join('')+'</section><h2 class="center">Septiembre 2026</h2><section class="statgrid"><div><b>'+total+'</b><small>Total incidencias</small></div><div class="green"><b>'+res+'</b><small>Resueltas</small></div><div class="amber"><b>'+proc+'</b><small>En proceso</small></div><div class="red"><b>'+pend+'</b><small>Pendientes</small></div></section><section class="card"><h2>Por departamentos</h2>'+Object.entries(zones).map(([z,n])=>'<div class="dept"><span>'+z+'</span><b>'+n+' ('+(total?Math.round(n/total*100):0)+'%)</b></div>').join('')+'<button class="historylink" data-view="history">Ver histórico por meses ›</button></section>')}
function history(){let base=[['Septiembre',80],['Agosto',64],['Julio',71],['Junio',55],['Mayo',48],['Abril',62],['Marzo',59],['Febrero',46],['Enero',52]];return shell('Histórico','<section class="card"><select class="year"><option>2026</option></select>'+base.map(([m,n])=>'<div class="month"><span>'+m+'</span><span><b>'+n+'</b> &nbsp;›</span></div>').join('')+'</section>',true)}
function settings(){return shell('Ajustes','<h3 class="group">Mi cuenta</h3><section class="card account"><span class="usericon">●</span><div><b>Encargado 1</b><small>Acceso mediante código</small></div><b>›</b></section><h3 class="group">Aplicación</h3><section class="card settingslist"><button>♧ <span>Notificaciones</span> ›</button><button>◎ <span>Idioma</span> ›</button><button id="dark">☾ <span>Modo oscuro</span><i class="switch '+(state.dark?'yes':'')+'"></i></button><button>ⓘ <span>Información</span> ›</button></section><section class="card"><button class="logout" id="logout">↪ &nbsp; Cerrar sesión</button></section>')}
function render(){document.getElementById('app').innerHTML=state.view==='login'?login():state.view==='home'?home():state.view==='list'?list():state.view==='create'?create():state.view==='stats'?stats():state.view==='history'?history():state.view==='detail'?detail():settings();bind()}
function bind(){
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));
document.querySelectorAll('.inc').forEach(x=>x.onclick=()=>{state.selected=x.dataset.id;state.view='detail';render()});
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;render()});
document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{state.period=b.dataset.period;render()});
document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{let k=b.dataset.key;if(k==='⌫')state.code=state.code.slice(0,-1);else if(k==='→'){if(state.code==='12345'){state.view='home';state.code=''}else{state.code='';render();document.getElementById('err').textContent='Código incorrecto';return}}else if(state.code.length<5)state.code+=k;render()});
let ph=document.getElementById('photo');if(ph)ph.onchange=e=>{let file=e.target.files&&e.target.files[0];if(!file)return;if(!file.type.startsWith('image/')){alert('Selecciona una fotografía válida');return}if(file.size>15*1024*1024){alert('La fotografía es demasiado grande');return}let reader=new FileReader();reader.onerror=()=>alert('No se pudo leer la fotografía');reader.onload=()=>{let image=new Image();image.onerror=()=>alert('No se pudo procesar la fotografía');image.onload=()=>{let max=1280,ratio=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*ratio));canvas.height=Math.max(1,Math.round(image.height*ratio));let ctx=canvas.getContext('2d');ctx.drawImage(image,0,0,canvas.width,canvas.height);let p=document.getElementById('preview');if(p){p.src=canvas.toDataURL('image/jpeg',0.72);p.style.display='block'}};image.src=reader.result};reader.readAsDataURL(file)};
let s=document.getElementById('save');if(s)s.onclick=()=>{let title=document.getElementById('title').value.trim();if(!title)return alert('Escribe un título');if(title.length>120)return alert('El título es demasiado largo');let preview=document.getElementById('preview'),img=preview&&preview.src&&!preview.src.endsWith('/')?preview.src:'';let next=Math.max(486,...incidents.map(x=>Number(String(x.id).replace(/\D/g,''))||0))+1;let item={id:'INC-'+String(next).padStart(5,'0'),title,desc:document.getElementById('desc').value.trim().slice(0,1000),zone:document.getElementById('zone').value,priority:document.getElementById('priority').value,status:'Nueva',date:new Date().toISOString(),updated:new Date().toISOString(),creator:'Encargado 1',img};incidents.push(item);if(!save()){incidents.pop();return}state.view='home';render()};
let st=document.getElementById('status');if(st)st.onclick=()=>{let i=incidents.find(x=>x.id===state.selected),seq=['Nueva','En proceso','Resuelta'];i.status=seq[(seq.indexOf(i.status)+1)%3];i.updated=new Date().toISOString();save();render()};
let d=document.getElementById('dark');if(d)d.onclick=()=>{state.dark=!state.dark;localStorage.setItem('inoxcenter-dark',state.dark?'1':'0');render()};
let bk=document.getElementById('back');if(bk)bk.onclick=()=>{state.view=state.history.pop()||'home';render()};
let lo=document.getElementById('logout');if(lo)lo.onclick=()=>{state.view='login';state.code='';render()}
}render();